server:
  port: 9000

#服务的名称
spring:
  application:
    name: api-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
zuul:
  routes:
    # 1. 默认的,当加上zuul网关组件后,可以通过ip:port/application-name/api的形式来通过网关访问在eureka中注册的服务.
    # 2. 地址相同后面的会覆盖前面的,所以最好细粒度的设定路径
    # 3. 且,下面开放的路径是公网访问路径,请求指定服务后后进行拦截然后在访问内网中可以访问的微服务程序
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
  # 统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  # 处理http请求头为空的问题： 因为一些敏感的请求数据不会被一同转发到内网中的微服务程序,如: RequestHeader: Cookie, Set-Cookie, Authentication
  # 那么将这些zuul的特殊配置设置为空就好
  sensitive-headers: 